version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.12 
    restart: always
    command: /bin/bash -c "tar -xvzf /tmp/bundle.tar.gz -C / && /entrypoint.sh"
    ports: 
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:8123:8123'
    volumes:
      - ./tmp/clickhouse-server-custom-config.xml:/etc/clickhouse-server/config.d/clickhouse-server-custom-config.xml:ro
      - ${BUNDLE_PATH:-./tmp/bundle.tar.gz}:/tmp/bundle.tar.gz:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
      - ETHEREUM_RPC_ENDPOINT=${ETHEREUM_RPC_ENDPOINT}
      - ETHEREUM_RPC_MAX_CONCURRENT_REQUESTS=${ETHEREUM_RPC_MAX_CONCURRENT_REQUESTS}
      - ETHEREUM_RPC_MAX_BATCH_SIZE=${ETHEREUM_RPC_MAX_BATCH_SIZE}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
